### ISSUE TITLE
I have noscript installed

### ISSUE THREAD

**Issue by pocketfood** [dxa4481/Pastejacking#2]
With noscript installed i dont have to worry about hidden scripts running in the background. This isnt an issue just a comment for everyone to install this plugin.
[NoScript.net](https://noscript.net/)

**Comment by dxa4481** [comment]
While this can help in some cases, this actually won't protect you from pasting content into the terminal. It can be done with pure html/css as seen here
https://thejh.net/misc/website-terminal-copy-paste
