### ISSUE TITLE
Doesn't work with Safari

### ISSUE THREAD

**Issue by RobertDeRose** [dxa4481/Pastejacking#3]
:)

**Comment by wsarles** [comment]
Agree. Safari 9.1.2 here. Alfred clipboard manager proof:[ http://imgur.com/8xlZBJ2](http://imgur.com/8xlZBJ2)

**Comment by naugtur** [comment]
well, as many other web features for the last 2 years. you'd have to wait till they introduce the feature

**Comment by martinczerwi** [comment]
Delaying the removal of the childNode made it work for me. Although I had to try different timeouts, you can try it yourself:

```
setTimeout(function(){
    document.body.removeChild(textArea);
}, 60);
```

Note that although the console says "Copying text command was unsuccessful" the clipboard is filled with the command. Maybe there's some side effect involved here.

**Comment by crazy4groovy** [comment]
I don't have a Mac, but I'm curious if just setting the textarea's `style="display:none"` would essentially remove it (from a user's perspective), while keeping it in the DOM long enough?

**Comment by dxa4481** [comment]
It does now https://security.love/Pastejacking/
