### ISSUE TITLE
Doesn't work with right click-> copy,  nor with auto-copy-on-highlight (linux/Mac)

### ISSUE THREAD

**Issue by mboyd1** [dxa4481/Pastejacking#4]
neat trick, but it doesn't pastejack if I copy with right click-> copy,  nor in Linux which auto copies text when selected, or with Firefox add-ons which do the same in Mac OS X.   I don't know if there is a solution to that, but maybe you can add it to the 'How do you protect yourself' section of the readme

**Comment by dxa4481** [comment]
Right now the event handler registered is the down key, however one could register on-click.

Additionally both of the proposed methods I don't think would be effective against the older css+html hidding method https://thejh.net/misc/website-terminal-copy-paste
